# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.destroy_all
Student.destroy_all
StudentGrade.destroy_all
Teacher.destroy_all
Course.destroy_all
Admin.destroy_all
Attendance.destroy_all

#teachers
user1 = User.create!(email: 'Michael', first_name: 'Michael', last_name: 'Louis', password:'starwars', role: 'teacher')
user17 = User.create!(email: 'Elizabeth', first_name: 'Elizabeth', last_name: 'Ketchum', password:'starwars', role: 'teacher')
user18 = User.create!(email: 'Marigold', first_name: 'Marigold', last_name: 'Rosas', password:'starwars', role: 'teacher')

#students
user2 = User.create!(email: 'Joe', first_name: 'Joe', last_name: 'Johnson', password:'starwars', role: 'student')
user4 = User.create!(email: 'Liz', first_name: 'Liz', last_name: 'Lucas', password:'starwars', role: 'student')
user5 = User.create!(email: 'Jackie', first_name: 'Jackie', last_name: 'Bastian', password:'starwars', role: 'student')
user7 = User.create!(email: 'Micael', first_name: 'Micael', last_name: 'Lucif', password:'starwars', role: 'student')
user6 = User.create!(email: 'John', first_name: 'John', last_name: 'Kiln', password:'starwars', role: 'student')
user8 = User.create!(email: 'Louis', first_name: 'Louis', last_name: 'Mischer', password:'starwars', role: 'student')
user9 = User.create!(email: 'Mary', first_name: 'Mary', last_name: 'Golden', password:'starwars', role: 'student')
user10 = User.create!(email: 'Joseph', first_name: 'Joseph', last_name: 'Ronald', password:'starwars', role: 'student')
user11 = User.create!(email: 'Luke', first_name: 'Luke', last_name: 'Darby', password:'starwars', role: 'student')
user12 = User.create!(email: 'Obi', first_name: 'Obi', last_name: 'Jenkins', password:'starwars', role: 'student')
user13= User.create!(email: 'Richie', first_name: 'Richie', last_name: 'Bender', password:'starwars', role: 'student')
user14= User.create!(email: 'Hugo', first_name: 'Hugo', last_name: 'Xhaxa', password:'starwars', role: 'student')
user15 = User.create!(email: 'Charlorette', first_name: 'Charlorette', last_name: 'Jimenez', password:'starwars', role: 'student')
user16= User.create!(email: 'Michael1', first_name: 'Michael', last_name: 'Lute', password:'starwars', role: 'student')

user19 = User.create!(email: 'Joseph1', first_name: 'Joseph', last_name: 'Murals', password:'starwars', role: 'student')
user20 = User.create!(email: 'Lucy', first_name: 'Lucy', last_name: 'Schumacher', password:'starwars', role: 'student')
user21 = User.create!(email: 'May', first_name: 'May', last_name: 'Townsend', password:'starwars', role: 'student')
user22 = User.create!(email: 'Autumn', first_name: 'Autumn', last_name: 'Martinez', password:'starwars', role: 'student')
user23 = User.create!(email: 'Esperanza', first_name: 'Esperanza', last_name: 'Augusto', password:'starwars', role: 'student')
user24 = User.create!(email: 'Peter', first_name: 'Peter', last_name: 'Lopez', password:'starwars', role: 'student')
user25 = User.create!(email: 'William', first_name: 'William', last_name: 'Gerrard', password:'starwars', role: 'student')
user26 = User.create!(email: 'Carlos', first_name: 'Carlos', last_name: 'Davis', password:'starwars', role: 'student')
user27 = User.create!(email: 'Walter', first_name: 'Walter', last_name: 'Hughes', password:'starwars', role: 'student')
user28 = User.create!(email: 'Ezra', first_name: 'Ezra', last_name: 'Angelou', password:'starwars', role: 'student')
user29 = User.create!(email: 'Eliot', first_name: 'Eliot', last_name: 'Cox', password:'starwars', role: 'student')

user30 = User.create!(email: 'Greg', first_name: 'Greg', last_name: 'Flemming', password:'starwars', role: 'student')
user31 = User.create!(email: 'Michelle', first_name: 'Michelle', last_name: 'Helter', password:'starwars', role: 'student')
user32 = User.create!(email: 'Lisa', first_name: 'Lisa', last_name: 'Beck', password:'starwars', role: 'student')
user33 = User.create!(email: 'George', first_name: 'George', last_name: 'Moradian', password:'starwars', role: 'student')
user34 = User.create!(email: 'Jan', first_name: 'Jan', last_name: 'Josephs', password:'starwars', role: 'student')
user35= User.create!(email: 'June', first_name: 'June', last_name: 'Judah', password:'starwars', role: 'student')
user36 = User.create!(email: 'August', first_name: 'August', last_name: 'Ceasar', password:'starwars', role: 'student')
user37 = User.create!(email: 'Krista', first_name: 'Krista', last_name: 'Peters', password:'starwars', role: 'student')
user38 = User.create!(email: 'Thomas', first_name: 'Thomas', last_name: 'Heimberger', password:'starwars', role: 'student')
user39 = User.create!(email: 'Corey', first_name: 'Corey', last_name: 'Ladovsky', password:'starwars', role: 'student')
user40 = User.create!(email: 'Kristina', first_name: 'Kristina', last_name: 'Fazza', password:'starwars', role: 'student')





#admin
user3 =  User.create!(email: 'Jack', first_name: 'Jack', last_name: 'DiCosta', password:'starwars', role: 'admin')


#teachers
teacher1 = Teacher.create!(user_id: user1.id, department: 'Literature' )
teacher2 = Teacher.create!(user_id: user17.id, department: 'Mathematics' )
teacher3 = Teacher.create!(user_id: user18.id, department: 'Biology' )


#students
student1 = Student.create!(user_id: user2.id)
student2 = Student.create!(user_id: user4.id)
student3 = Student.create!(user_id: user5.id)
student4 = Student.create!(user_id: user6.id)
student5 = Student.create!(user_id: user7.id)
student6 = Student.create!(user_id: user8.id)
student7 = Student.create!(user_id: user9.id)
student8 = Student.create!(user_id: user10.id)
student9 = Student.create!(user_id: user11.id)
student10 = Student.create!(user_id: user12.id)
student11 = Student.create!(user_id: user13.id)
student12 = Student.create!(user_id: user14.id)
student13 = Student.create!(user_id: user15.id)
student14 = Student.create!(user_id: user16.id)

student15 = Student.create!(user_id: user19.id)
student16 = Student.create!(user_id: user20.id)
student17 = Student.create!(user_id: user21.id)
student18 = Student.create!(user_id: user22.id)
student19 = Student.create!(user_id: user23.id)
student20 = Student.create!(user_id: user24.id)
student21 = Student.create!(user_id: user25.id)
student22 = Student.create!(user_id: user26.id)
student23 = Student.create!(user_id: user27.id)
student24 = Student.create!(user_id: user28.id)
student25 = Student.create!(user_id: user29.id)

student26 = Student.create!(user_id: user30.id)
student27 = Student.create!(user_id: user31.id)
student28 = Student.create!(user_id: user32.id)
student29 = Student.create!(user_id: user33.id)
student30 = Student.create!(user_id: user34.id)
student31 = Student.create!(user_id: user35.id)
student32 = Student.create!(user_id: user36.id)
student33 = Student.create!(user_id: user37.id)
student34 = Student.create!(user_id: user38.id)
student35 = Student.create!(user_id: user39.id)
student36 = Student.create!(user_id: user40.id)



#admins

Admin.create!(title: 'Dean of Admissions', user_id: user3.id)

#courses
course1 = Course.create!(name: 'English Literature 101', teacher_id: teacher1.id)
course2 = Course.create!(name: 'Philosophy of Early 19th Century Russian Literature', teacher_id: teacher1.id)
course3 = Course.create!(name: 'Shakespeare\'s Ghost', teacher_id: teacher1.id)
course4 = Course.create!(name: 'American Poetry', teacher_id: teacher1.id)

course5 = Course.create!(name: 'Linear Algebra', teacher_id: teacher2.id)
course6 = Course.create!(name: 'Calculus 302', teacher_id: teacher2.id)
course7 = Course.create!(name: 'Theoretical Algebra', teacher_id: teacher2.id)

course8 = Course.create!(name: 'Biology 201', teacher_id: teacher3.id)
course9 = Course.create!(name: 'Observing Living Beings', teacher_id: teacher3.id)
course10 = Course.create!(name: 'Cellular Analysis', teacher_id: teacher3.id)


#attendances
Attendance.create!(student_id: student1.id, course_id:course1.id)
Attendance.create!(student_id: student2.id, course_id:course1.id)
Attendance.create!(student_id: student3.id, course_id:course1.id)
Attendance.create!(student_id: student4.id, course_id:course1.id)
Attendance.create!(student_id: student5.id, course_id:course1.id)
Attendance.create!(student_id: student6.id, course_id:course1.id)
Attendance.create!(student_id: student7.id, course_id:course1.id)
Attendance.create!(student_id: student8.id, course_id:course1.id)
Attendance.create!(student_id: student9.id, course_id:course1.id)
Attendance.create!(student_id: student10.id, course_id:course1.id)
Attendance.create!(student_id: student11.id, course_id:course1.id)
Attendance.create!(student_id: student12.id, course_id:course1.id)
Attendance.create!(student_id: student13.id, course_id:course1.id)
Attendance.create!(student_id: student14.id, course_id:course1.id)
#######
Attendance.create!(student_id: student1.id, course_id:course2.id)
Attendance.create!(student_id: student2.id, course_id:course2.id)
Attendance.create!(student_id: student3.id, course_id:course2.id)
Attendance.create!(student_id: student4.id, course_id:course2.id)
Attendance.create!(student_id: student5.id, course_id:course2.id)
Attendance.create!(student_id: student6.id, course_id:course2.id)
Attendance.create!(student_id: student7.id, course_id:course2.id)
Attendance.create!(student_id: student8.id, course_id:course2.id)
Attendance.create!(student_id: student9.id, course_id:course2.id)
Attendance.create!(student_id: student10.id, course_id:course2.id)
Attendance.create!(student_id: student11.id, course_id:course2.id)
Attendance.create!(student_id: student12.id, course_id:course2.id)
Attendance.create!(student_id: student13.id, course_id:course2.id)
Attendance.create!(student_id: student14.id, course_id:course2.id)
###
Attendance.create!(student_id: student1.id, course_id:course3.id)
Attendance.create!(student_id: student2.id, course_id:course3.id)
Attendance.create!(student_id: student3.id, course_id:course3.id)
Attendance.create!(student_id: student4.id, course_id:course3.id)
Attendance.create!(student_id: student5.id, course_id:course3.id)
Attendance.create!(student_id: student6.id, course_id:course3.id)
Attendance.create!(student_id: student7.id, course_id:course3.id)
Attendance.create!(student_id: student8.id, course_id:course3.id)
Attendance.create!(student_id: student9.id, course_id:course3.id)
Attendance.create!(student_id: student10.id, course_id:course3.id)
Attendance.create!(student_id: student11.id, course_id:course3.id)
Attendance.create!(student_id: student12.id, course_id:course3.id)
Attendance.create!(student_id: student13.id, course_id:course3.id)
Attendance.create!(student_id: student14.id, course_id:course3.id)
###
Attendance.create!(student_id: student1.id, course_id:course4.id)
Attendance.create!(student_id: student2.id, course_id:course4.id)
Attendance.create!(student_id: student3.id, course_id:course4.id)
Attendance.create!(student_id: student4.id, course_id:course4.id)
Attendance.create!(student_id: student5.id, course_id:course4.id)
Attendance.create!(student_id: student6.id, course_id:course4.id)
Attendance.create!(student_id: student7.id, course_id:course4.id)
Attendance.create!(student_id: student8.id, course_id:course4.id)
Attendance.create!(student_id: student9.id, course_id:course4.id)
Attendance.create!(student_id: student10.id, course_id:course4.id)
Attendance.create!(student_id: student11.id, course_id:course4.id)
Attendance.create!(student_id: student12.id, course_id:course4.id)
Attendance.create!(student_id: student13.id, course_id:course4.id)
Attendance.create!(student_id: student14.id, course_id:course4.id)
### New Batch
Attendance.create!(student_id: student15.id, course_id:course5.id)
Attendance.create!(student_id: student16.id, course_id:course5.id)
Attendance.create!(student_id: student17.id, course_id:course5.id)
Attendance.create!(student_id: student18.id, course_id:course5.id)
Attendance.create!(student_id: student19.id, course_id:course5.id)
Attendance.create!(student_id: student20.id, course_id:course5.id)
Attendance.create!(student_id: student21.id, course_id:course5.id)
Attendance.create!(student_id: student22.id, course_id:course5.id)
Attendance.create!(student_id: student23.id, course_id:course5.id)
Attendance.create!(student_id: student24.id, course_id:course5.id)
Attendance.create!(student_id: student25.id, course_id:course5.id)
###
Attendance.create!(student_id: student15.id, course_id:course6.id)
Attendance.create!(student_id: student16.id, course_id:course6.id)
Attendance.create!(student_id: student17.id, course_id:course6.id)
Attendance.create!(student_id: student18.id, course_id:course6.id)
Attendance.create!(student_id: student19.id, course_id:course6.id)
Attendance.create!(student_id: student20.id, course_id:course6.id)
Attendance.create!(student_id: student21.id, course_id:course6.id)
Attendance.create!(student_id: student22.id, course_id:course6.id)
Attendance.create!(student_id: student23.id, course_id:course6.id)
Attendance.create!(student_id: student24.id, course_id:course6.id)
Attendance.create!(student_id: student25.id, course_id:course6.id)
###
Attendance.create!(student_id: student15.id, course_id:course7.id)
Attendance.create!(student_id: student16.id, course_id:course7.id)
Attendance.create!(student_id: student17.id, course_id:course7.id)
Attendance.create!(student_id: student18.id, course_id:course7.id)
Attendance.create!(student_id: student19.id, course_id:course7.id)
Attendance.create!(student_id: student20.id, course_id:course7.id)
Attendance.create!(student_id: student21.id, course_id:course7.id)
Attendance.create!(student_id: student22.id, course_id:course7.id)
Attendance.create!(student_id: student23.id, course_id:course7.id)
Attendance.create!(student_id: student24.id, course_id:course7.id)
Attendance.create!(student_id: student25.id, course_id:course7.id)
###
Attendance.create!(student_id: student26.id, course_id:course8.id)
Attendance.create!(student_id: student27.id, course_id:course8.id)
Attendance.create!(student_id: student28.id, course_id:course8.id)
Attendance.create!(student_id: student29.id, course_id:course8.id)
Attendance.create!(student_id: student30.id, course_id:course8.id)
Attendance.create!(student_id: student31.id, course_id:course8.id)
Attendance.create!(student_id: student32.id, course_id:course8.id)
Attendance.create!(student_id: student33.id, course_id:course8.id)
Attendance.create!(student_id: student34.id, course_id:course8.id)
Attendance.create!(student_id: student35.id, course_id:course8.id)
Attendance.create!(student_id: student36.id, course_id:course8.id)
###
Attendance.create!(student_id: student26.id, course_id:course9.id)
Attendance.create!(student_id: student27.id, course_id:course9.id)
Attendance.create!(student_id: student28.id, course_id:course9.id)
Attendance.create!(student_id: student29.id, course_id:course9.id)
Attendance.create!(student_id: student30.id, course_id:course9.id)
Attendance.create!(student_id: student31.id, course_id:course9.id)
Attendance.create!(student_id: student32.id, course_id:course9.id)
Attendance.create!(student_id: student33.id, course_id:course9.id)
Attendance.create!(student_id: student34.id, course_id:course9.id)
Attendance.create!(student_id: student35.id, course_id:course9.id)
Attendance.create!(student_id: student36.id, course_id:course9.id)
###
Attendance.create!(student_id: student26.id, course_id:course10.id)
Attendance.create!(student_id: student27.id, course_id:course10.id)
Attendance.create!(student_id: student28.id, course_id:course10.id)
Attendance.create!(student_id: student29.id, course_id:course10.id)
Attendance.create!(student_id: student30.id, course_id:course10.id)
Attendance.create!(student_id: student31.id, course_id:course10.id)
Attendance.create!(student_id: student32.id, course_id:course10.id)
Attendance.create!(student_id: student33.id, course_id:course10.id)
Attendance.create!(student_id: student34.id, course_id:course10.id)
Attendance.create!(student_id: student35.id, course_id:course10.id)
Attendance.create!(student_id: student36.id, course_id:course10.id)

#student grades 1-14
StudentGrade.create!(student_id: student1.id, course_id:course1.id, grade: 72)
StudentGrade.create!(student_id: student2.id, course_id:course1.id, grade: 77)
StudentGrade.create!(student_id: student3.id, course_id:course1.id, grade: 80)
StudentGrade.create!(student_id: student4.id, course_id:course1.id, grade: 65)
StudentGrade.create!(student_id: student5.id, course_id:course1.id, grade: 88)
StudentGrade.create!(student_id: student6.id, course_id:course1.id, grade: 88)
StudentGrade.create!(student_id: student7.id, course_id:course1.id, grade: 55)
StudentGrade.create!(student_id: student8.id, course_id:course1.id, grade: 79)
StudentGrade.create!(student_id: student9.id, course_id:course1.id, grade: 88)
StudentGrade.create!(student_id: student10.id, course_id:course1.id, grade: 82)
StudentGrade.create!(student_id: student11.id, course_id:course1.id, grade: 84)
StudentGrade.create!(student_id: student12.id, course_id:course1.id, grade: 73)
StudentGrade.create!(student_id: student13.id, course_id:course1.id, grade: 95)
StudentGrade.create!(student_id: student14.id, course_id:course1.id, grade: 90)
#####
StudentGrade.create!(student_id: student1.id, course_id:course2.id, grade: 78)
StudentGrade.create!(student_id: student2.id, course_id:course2.id, grade: 72)
StudentGrade.create!(student_id: student3.id, course_id:course2.id, grade: 85)
StudentGrade.create!(student_id: student4.id, course_id:course2.id, grade: 90)
StudentGrade.create!(student_id: student5.id, course_id:course2.id, grade: 93)
StudentGrade.create!(student_id: student6.id, course_id:course2.id, grade: 84)
StudentGrade.create!(student_id: student7.id, course_id:course2.id, grade: 79)
StudentGrade.create!(student_id: student8.id, course_id:course2.id, grade: 69)
StudentGrade.create!(student_id: student9.id, course_id:course2.id, grade: 79)
StudentGrade.create!(student_id: student10.id, course_id:course2.id, grade: 78)
StudentGrade.create!(student_id: student11.id, course_id:course2.id, grade: 77)
StudentGrade.create!(student_id: student12.id, course_id:course2.id, grade: 88)
StudentGrade.create!(student_id: student13.id, course_id:course2.id, grade: 85)
StudentGrade.create!(student_id: student14.id, course_id:course2.id, grade: 88)

StudentGrade.create!(student_id: student1.id, course_id:course3.id, grade: 88)
StudentGrade.create!(student_id: student2.id, course_id:course3.id, grade: 88)
StudentGrade.create!(student_id: student3.id, course_id:course3.id, grade: 95)
StudentGrade.create!(student_id: student4.id, course_id:course3.id, grade: 97)
StudentGrade.create!(student_id: student5.id, course_id:course3.id, grade: 97)
StudentGrade.create!(student_id: student6.id, course_id:course3.id, grade: 66)
StudentGrade.create!(student_id: student7.id, course_id:course3.id, grade: 75)
StudentGrade.create!(student_id: student8.id, course_id:course3.id, grade: 75)
StudentGrade.create!(student_id: student9.id, course_id:course3.id, grade: 78)
StudentGrade.create!(student_id: student10.id, course_id:course3.id, grade: 80)
StudentGrade.create!(student_id: student11.id, course_id:course3.id, grade: 90)
StudentGrade.create!(student_id: student12.id, course_id:course3.id, grade: 93)
StudentGrade.create!(student_id: student13.id, course_id:course3.id, grade: 92)
StudentGrade.create!(student_id: student14.id, course_id:course3.id, grade: 79)

StudentGrade.create!(student_id: student1.id, course_id:course4.id, grade: 68)
StudentGrade.create!(student_id: student2.id, course_id:course4.id, grade: 90)
StudentGrade.create!(student_id: student3.id, course_id:course4.id, grade: 97)
StudentGrade.create!(student_id: student4.id, course_id:course4.id, grade: 99)
StudentGrade.create!(student_id: student5.id, course_id:course4.id, grade: 80)
StudentGrade.create!(student_id: student6.id, course_id:course4.id, grade: 79)
StudentGrade.create!(student_id: student7.id, course_id:course4.id, grade: 80)
StudentGrade.create!(student_id: student8.id, course_id:course4.id, grade: 85)
StudentGrade.create!(student_id: student9.id, course_id:course4.id, grade: 75)
StudentGrade.create!(student_id: student10.id, course_id:course4.id, grade: 74)
StudentGrade.create!(student_id: student11.id, course_id:course4.id, grade: 73)
StudentGrade.create!(student_id: student12.id, course_id:course4.id, grade: 80)
StudentGrade.create!(student_id: student13.id, course_id:course4.id, grade: 88)
StudentGrade.create!(student_id: student14.id, course_id:course4.id, grade: 89)

#15-25
StudentGrade.create!(student_id: student15.id, course_id:course5.id, grade: 56)
StudentGrade.create!(student_id: student16.id, course_id:course5.id, grade: 77)
StudentGrade.create!(student_id: student17.id, course_id:course5.id, grade: 64)
StudentGrade.create!(student_id: student18.id, course_id:course5.id, grade:70)
StudentGrade.create!(student_id: student19.id, course_id:course5.id, grade: 88)
StudentGrade.create!(student_id: student20.id, course_id:course5.id, grade: 90)
StudentGrade.create!(student_id: student21.id, course_id:course5.id, grade: 96)
StudentGrade.create!(student_id: student22.id, course_id:course5.id, grade: 97)
StudentGrade.create!(student_id: student23.id, course_id:course5.id, grade: 98)
StudentGrade.create!(student_id: student24.id, course_id:course5.id, grade: 88)
StudentGrade.create!(student_id: student25.id, course_id:course5.id, grade: 82)

StudentGrade.create!(student_id: student15.id, course_id:course6.id, grade: 88)
StudentGrade.create!(student_id: student16.id, course_id:course6.id, grade: 76)
StudentGrade.create!(student_id: student17.id, course_id:course6.id, grade: 86)
StudentGrade.create!(student_id: student18.id, course_id:course6.id, grade: 88)
StudentGrade.create!(student_id: student19.id, course_id:course6.id, grade: 83)
StudentGrade.create!(student_id: student20.id, course_id:course6.id, grade: 94)
StudentGrade.create!(student_id: student21.id, course_id:course6.id, grade: 94)
StudentGrade.create!(student_id: student22.id, course_id:course6.id, grade: 94)
StudentGrade.create!(student_id: student23.id, course_id:course6.id, grade: 96)
StudentGrade.create!(student_id: student24.id, course_id:course6.id, grade: 97)
StudentGrade.create!(student_id: student25.id, course_id:course6.id, grade: 68)

StudentGrade.create!(student_id: student15.id, course_id:course7.id, grade: 76)
StudentGrade.create!(student_id: student16.id, course_id:course7.id, grade: 77)
StudentGrade.create!(student_id: student17.id, course_id:course7.id, grade: 85)
StudentGrade.create!(student_id: student18.id, course_id:course7.id, grade: 65)
StudentGrade.create!(student_id: student19.id, course_id:course7.id, grade: 67)
StudentGrade.create!(student_id: student20.id, course_id:course7.id, grade: 78)
StudentGrade.create!(student_id: student21.id, course_id:course7.id, grade: 88)
StudentGrade.create!(student_id: student22.id, course_id:course7.id, grade: 84)
StudentGrade.create!(student_id: student23.id, course_id:course7.id, grade: 83)
StudentGrade.create!(student_id: student24.id, course_id:course7.id, grade: 90)
StudentGrade.create!(student_id: student25.id, course_id:course7.id, grade: 97)
#26-
StudentGrade.create!(student_id: student26.id, course_id:course8.id, grade: 90)
StudentGrade.create!(student_id: student27.id, course_id:course8.id, grade: 90)
StudentGrade.create!(student_id: student28.id, course_id:course8.id, grade: 85)
StudentGrade.create!(student_id: student29.id, course_id:course8.id, grade: 79)
StudentGrade.create!(student_id: student30.id, course_id:course8.id, grade: 89)
StudentGrade.create!(student_id: student31.id, course_id:course8.id, grade: 88)
StudentGrade.create!(student_id: student32.id, course_id:course8.id, grade: 69)
StudentGrade.create!(student_id: student33.id, course_id:course8.id, grade: 70)
StudentGrade.create!(student_id: student34.id, course_id:course8.id, grade: 97)
StudentGrade.create!(student_id: student35.id, course_id:course8.id, grade: 94)
StudentGrade.create!(student_id: student36.id, course_id:course8.id, grade: 98)

StudentGrade.create!(student_id: student26.id, course_id:course9.id, grade: 69)
StudentGrade.create!(student_id: student27.id, course_id:course9.id, grade: 87)
StudentGrade.create!(student_id: student28.id, course_id:course9.id, grade: 76)
StudentGrade.create!(student_id: student29.id, course_id:course9.id, grade: 76)
StudentGrade.create!(student_id: student30.id, course_id:course9.id, grade: 88)
StudentGrade.create!(student_id: student31.id, course_id:course9.id, grade: 88)
StudentGrade.create!(student_id: student32.id, course_id:course9.id, grade: 75)
StudentGrade.create!(student_id: student33.id, course_id:course9.id, grade: 79)
StudentGrade.create!(student_id: student34.id, course_id:course9.id, grade: 90)
StudentGrade.create!(student_id: student35.id, course_id:course9.id, grade: 90)
StudentGrade.create!(student_id: student36.id, course_id:course9.id, grade: 98)

StudentGrade.create!(student_id: student26.id, course_id:course10.id, grade: 89)
StudentGrade.create!(student_id: student27.id, course_id:course10.id, grade: 98)
StudentGrade.create!(student_id: student28.id, course_id:course10.id, grade: 76)
StudentGrade.create!(student_id: student29.id, course_id:course10.id, grade: 65)
StudentGrade.create!(student_id: student30.id, course_id:course10.id, grade: 78)
StudentGrade.create!(student_id: student31.id, course_id:course10.id, grade: 90)
StudentGrade.create!(student_id: student32.id, course_id:course10.id, grade: 90)
StudentGrade.create!(student_id: student33.id, course_id:course10.id, grade: 97)
StudentGrade.create!(student_id: student34.id, course_id:course10.id, grade: 76)
StudentGrade.create!(student_id: student35.id, course_id:course10.id, grade: 87)
StudentGrade.create!(student_id: student36.id, course_id:course10.id, grade: 88)
